name: backend CICD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: wanderlust-mega-project-backend
  ECS_CLUSTER: wanderlust-mega-project-cluster
  ECS_SERVICE: backend-task-service-tf

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Show Node Version
        run: node --version

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-source-${{ matrix.node-version }}
          path: backend/  

  deploy-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Docker Image
       # run: docker build -t wanderlust-mega-project-backend ./backend
        run: docker build -t ${{ env.ECR_REPOSITORY }} ./backend
      - name: Tag Docker Image
       # run: docker tag wanderlust-mega-project-backend:latest 060679227712.dkr.ecr.us-east-2.amazonaws.com/wanderlust-mega-project-backend:latest
        run: docker tag ${{ env.ECR_REPOSITORY }}:latest 060679227712.dkr.ecr.us-east-2.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
      - name: Push Docker Image to ECR
       # run: docker push 060679227712.dkr.ecr.us-east-2.amazonaws.com/wanderlust-mega-project-backend:latest
        run: docker push 060679227712.dkr.ecr.us-east-2.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
      - name: Deploy to ECS
      #  run: aws ecs update-service --cluster wanderlust-mega-project-cluster --service backend-task-service-tf --force-new-deployment --region us-east-2
         run: aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --region ${{ env.AWS_REGION }}

